version: 0.2
phases:
  pre-build:
    commands:
      - cd backend
  install:
    commands:
      - cd backend

      - npm install

      - pip install --upgrade awscli
artifacts:
  files:
    - "**/*"
  base-directory: "./backend"
